[build]
command = "node fetch-content.js && hugo -b https://docs.masterix.org"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.55.5"
HUGO_ENV = "production"

[[redirects]]
  from = "https://masterix21-docs.netlify.com/*"
  to = "https://docs.masterix.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/laravel-addressable/"
  to = "/laravel-addressable/v1/introduction"
  status = 301
  force = true

[[redirects]]
  from = "/x-blade-components/"
  to = "/x-blade-components/v1/introduction"
  status = 301
  force = true
